# Generated by Django 4.2 on 2026-04-14 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aitext', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seo_title', models.CharField(blank=True, help_text='Если не указано, будет использовано название категории', max_length=200, null=True, verbose_name='SEO заголовок (title)')),
                ('seo_description', models.TextField(blank=True, help_text='Если не указано, будет использовано описание категории', null=True, verbose_name='SEO описание (description)')),
                ('seo_keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, null=True, verbose_name='SEO ключевые слова (keywords)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='blog/previews/', verbose_name='Превью (изображение)')),
                ('preview_text', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('show_in_notification', models.BooleanField(default=False, verbose_name='Показывать в уведомлении')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Добавить на главную')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, help_text='Если не указано, будет использовано название статьи', max_length=200, null=True, verbose_name='SEO заголовок (title)')),
                ('seo_description', models.TextField(blank=True, help_text='Если не указано, будет использован preview_text статьи', null=True, verbose_name='SEO описание (description)')),
                ('seo_keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, null=True, verbose_name='SEO ключевые слова (keywords)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Категория')),
                ('neural_networks', models.ManyToManyField(blank=True, related_name='related_posts', to='aitext.neuralnetwork', verbose_name='Связанные нейросети')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at'],
            },
        ),
    ]
