# Generated by Django 6.0.6 on 2026-07-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='faq_items',
            field=models.JSONField(blank=True, default=list, help_text='Список {"question": ..., "answer": ...} для структурированных данных', verbose_name='FAQ (для FAQPage schema)'),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('fa', 'Persian'), ('tr', 'Turkish'), ('id', 'Indonesian'), ('ar', 'Arabic')], db_index=True, default='ru', help_text='Статьи под разные рынки — самостоятельный контент, не перевод одного источника (GLOBAL_EXPANSION_PLAN.md §4.3)', max_length=8, verbose_name='Язык'),
        ),
    ]
