# Generated by Django 4.2 on 2026-04-14 09:36

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('email_verification_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Токен подтверждения')),
                ('email_verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения')),
                ('pages_count', models.PositiveIntegerField(default=0, verbose_name='Количество звезд')),
                ('shadow_banned', models.BooleanField(default=False, verbose_name='Теневой бан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('rub_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс в рублях')),
                ('can_convert_to_rub', models.BooleanField(default=False, verbose_name='Можно конвертировать звёзды в рубли')),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Реферальный код')),
                ('referral_clicks', models.PositiveIntegerField(default=0, verbose_name='Количество переходов по ссылке')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('privacy', 'Политика конфиденциальности'), ('terms', 'Пользовательское соглашение')], max_length=20, unique=True, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Юридический документ',
                'verbose_name_plural': 'Юридические документы',
            },
        ),
        migrations.CreateModel(
            name='PageSaleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_page', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за 1 звезду')),
                ('min_pages_for_purchase', models.PositiveIntegerField(default=1, verbose_name='Минимальное количество звезд для покупки')),
                ('max_pages_for_purchase', models.PositiveIntegerField(default=100, verbose_name='Максимальное количество звезд для покупки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна продажа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройка продажи звезд',
                'verbose_name_plural': 'Настройки продажи звезд',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('stars', models.PositiveIntegerField(verbose_name='Количество звезд')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='Лимит использований (0 - безлимит)')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Уже использовано')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действителен до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='SiteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_text', models.TextField(help_text='Вставьте код счетчика', verbose_name='Текст счетчика')),
            ],
            options={
                'verbose_name': 'Счетчик сайта',
                'verbose_name_plural': 'Счетчики сайта',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='LUMEN', max_length=200, verbose_name='Заголовок главной страницы')),
                ('description', models.TextField(blank=True, default='Нейросети без VPN и сложностей', verbose_name='Описание для главной страницы')),
                ('keywords', models.CharField(blank=True, default='нейросети, AI, искусственный интеллект, генерация изображений, чат с AI', max_length=500, verbose_name='Ключевые слова (через запятую)')),
                ('inn', models.CharField(blank=True, default='ИНН: 1234567890', max_length=100, verbose_name='ИНН для футера')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('vk_url', models.URLField(blank=True, default='', verbose_name='Ссылка на группу ВКонтакте')),
                ('telegram_url', models.URLField(blank=True, default='', verbose_name='Ссылка на Telegram-канал')),
                ('blog_title', models.CharField(blank=True, default='Блог | LUMEN', max_length=200, verbose_name='Заголовок страницы блога')),
                ('blog_description', models.TextField(blank=True, default='Новости, статьи и обзоры нейросетей', verbose_name='Описание для страницы блога')),
                ('blog_keywords', models.CharField(blank=True, default='нейросети, искусственный интеллект, AI, новости, статьи', max_length=500, verbose_name='Ключевые слова для блога (через запятую)')),
                ('catalog_title', models.CharField(blank=True, default='Каталог нейросетей | LUMEN', max_length=200, verbose_name='Заголовок страницы каталога')),
                ('catalog_description', models.TextField(blank=True, default='Все нейросети в одном месте. Выбирайте и начинайте работу.', verbose_name='Описание для страницы каталога')),
                ('catalog_keywords', models.CharField(blank=True, default='нейросети, каталог AI, искусственный интеллект, модели', max_length=500, verbose_name='Ключевые слова для каталога (через запятую)')),
                ('support_email', models.EmailField(blank=True, default='support@example.com', max_length=254, verbose_name='Email поддержки')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('pages_count', models.PositiveIntegerField(verbose_name='Количество звезд')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость тарифа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатный тариф')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Срок действия (дней)')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Пробный тариф')),
                ('referral_bonus', models.PositiveIntegerField(default=0, help_text='Сколько рублей получит пригласивший пользователь при покупке этого тарифа', verbose_name='Реферальный бонус')),
                ('referral_bonus_stars', models.PositiveIntegerField(default=0, help_text='Сколько звёзд получит пригласивший пользователь при покупке этого тарифа', verbose_name='Реферальный бонус (звёзд)')),
                ('next_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tariff', verbose_name='Следующий тариф (для пробных)')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма вывода')),
                ('card_number', models.CharField(max_length=20, verbose_name='Номер карты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, verbose_name='Примечание администратора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос на вывод',
                'verbose_name_plural': 'Запросы на вывод',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='ID подписки')),
                ('robokassa_invoice_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID счета Robokassa')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('expires_at', models.DateTimeField(verbose_name='Дата окончания')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего платежа')),
                ('next_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата следующего платежа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Автопродление')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Истекла'), ('cancelled', 'Отменена'), ('pending', 'Ожидает оплаты')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('renewal_attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток продления')),
                ('max_renewal_attempts', models.PositiveIntegerField(default=6, verbose_name='Максимум попыток')),
                ('last_renewal_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка продления')),
                ('last_expiry_notification_sent', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего уведомления об истечении')),
                ('original_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_subscriptions', to='users.tariff', verbose_name='Исходный тариф (для пробного)')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка пользователя',
                'verbose_name_plural': 'Подписки пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество звезд')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата списания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spendings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Списание звезд',
                'verbose_name_plural': 'Списания звезд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'IP-адрес пользователя',
                'verbose_name_plural': 'IP-адреса пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата активности')),
                ('login_count', models.IntegerField(default=0, verbose_name='Количество заходов')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего захода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал активности пользователя',
                'verbose_name_plural': 'Журнал активности пользователей',
                'ordering': ['-date', '-last_login_time'],
            },
        ),
        migrations.CreateModel(
            name='UsedPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to='users.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_promocodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Использованный промокод',
                'verbose_name_plural': 'Использованные промокоды',
            },
        ),
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_rub', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма в рублях')),
                ('amount_stars', models.PositiveIntegerField(default=0, verbose_name='Сумма в звёздах')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реферальное начисление',
                'verbose_name_plural': 'Реферальные начисления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('subscription', 'Оплата подписки'), ('pages', 'Покупка звезд'), ('promo', 'Активация промокода')], default='subscription', max_length=20, verbose_name='Тип платежа')),
                ('invoice_id', models.CharField(db_index=True, max_length=100, verbose_name='ID счета')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('pages_count', models.PositiveIntegerField(default=0, verbose_name='Куплено звезд')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Способ оплаты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.paymenthistory', verbose_name='Материнский платеж')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.usersubscription', verbose_name='Подписка')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История платежей',
                'verbose_name_plural': 'История платежей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_user', to='users.usersubscription', verbose_name='Активная подписка'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_groups', related_query_name='customuser', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Пригласивший пользователь'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.tariff', verbose_name='Текущий тариф'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions', related_query_name='customuser', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'is_active', 'expires_at'], name='users_users_user_id_0ea9df_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['robokassa_invoice_id'], name='users_users_robokas_c8f624_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useripaddress',
            unique_together={('user', 'ip_address')},
        ),
        migrations.AlterUniqueTogether(
            name='useractivitylog',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='usedpromocode',
            unique_together={('user', 'promo_code')},
        ),
    ]
