# Generated by Django 4.2 on 2026-07-02 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_memory_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance_kopecks',
            field=models.BigIntegerField(default=0, help_text='Авторитетный баланс (1 звезда = 100 коп.). См. src/core/money.py, BILLING_MIGRATION_PLAN.md', verbose_name='Баланс, копейки'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='amount_kopecks',
            field=models.BigIntegerField(blank=True, help_text='Заполняется только для новых записей (после миграции биллинга). Историю не конвертируем — финансовый аудит.', null=True, verbose_name='Сумма, копейки'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='kopecks',
            field=models.BigIntegerField(default=0, help_text='Авто-синхронизируется с stars ×100 при сохранении', verbose_name='Начисление, копейки'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='balance_grant_kopecks',
            field=models.BigIntegerField(default=0, help_text='Авто-синхронизируется с pages_count ×100 при сохранении (1 звезда = 100 коп.)', verbose_name='Начисление на баланс, копейки'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='referral_bonus_kopecks',
            field=models.BigIntegerField(default=0, help_text='Авто-синхронизируется с referral_bonus_stars ×100 при сохранении', verbose_name='Реферальный бонус, копейки'),
        ),
        migrations.AddField(
            model_name='userspending',
            name='amount_kopecks',
            field=models.BigIntegerField(default=0, verbose_name='Списано, копейки'),
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kopecks', models.BigIntegerField(help_text='Знаковая величина: списание < 0, начисление > 0', verbose_name='Сумма, копейки')),
                ('balance_after', models.BigIntegerField(verbose_name='Баланс после операции, копейки')),
                ('type', models.CharField(choices=[('spend', 'Списание'), ('refund', 'Возврат'), ('topup', 'Пополнение'), ('subscription', 'Тариф'), ('promo', 'Промокод'), ('referral', 'Реферальный бонус'), ('xtr', 'Telegram Stars'), ('admin', 'Ручное начисление')], max_length=20, verbose_name='Тип операции')),
                ('reference', models.CharField(blank=True, default='', help_text='invoice_id / request_id / project_id — для идемпотентности начислений', max_length=128, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция баланса',
                'verbose_name_plural': 'Транзакции баланса',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='balancetransaction',
            index=models.Index(fields=['user', '-created_at'], name='balance_txn_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='balancetransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('type', 'reference'), name='uniq_balance_txn_type_reference'),
        ),
    ]
