# Generated by Django 4.2 on 2026-07-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_paymenthistory_promo_code_promocode_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancetransaction',
            name='type',
            field=models.CharField(choices=[('spend', 'Списание'), ('refund', 'Возврат'), ('topup', 'Пополнение'), ('subscription', 'Тариф'), ('promo', 'Промокод'), ('referral', 'Реферальный бонус'), ('xtr', 'Telegram Stars'), ('admin', 'Ручное начисление'), ('sandbox', 'Sandbox API')], max_length=20, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='pages_count',
            field=models.PositiveIntegerField(help_text='Сколько рублей зачисляется на баланс при покупке (legacy-название поля «звёзды»: 1 звезда = 1 ₽)', verbose_name='Начисление на баланс, ₽'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='referral_bonus',
            field=models.PositiveIntegerField(default=0, help_text='Сколько рублей на вывод (на карту) получит пригласивший при покупке этого тарифа', verbose_name='Реф. бонус на вывод, ₽'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='referral_bonus_stars',
            field=models.PositiveIntegerField(default=0, help_text='Сколько рублей на баланс получит пригласивший при покупке этого тарифа (legacy-название поля «звёзды»: 1 звезда = 1 ₽)', verbose_name='Реф. бонус на баланс, ₽'),
        ),
    ]
