# Generated by Django 4.2 (hand-authored to match modeltranslation's convention,
# see aitext/migrations/0052_category_name_en_category_name_ru_faq_answer_en_and_more.py)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_balancetransaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
