# Generated by Django 6.0.6 on 2026-07-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_withdrawalrequest_payout_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='content_ind',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='title_ind',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
    ]
