# Generated by Django 4.2 on 2026-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_stack_python_django_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='studioproject',
            name='max_kopecks_budget',
            field=models.BigIntegerField(default=0, verbose_name='Бюджет, копейки (0 = без лимита)'),
        ),
        migrations.AddField(
            model_name='studioproject',
            name='stars_reserved_kopecks',
            field=models.BigIntegerField(default=0, verbose_name='Зарезервировано, копейки'),
        ),
        migrations.AddField(
            model_name='studioproject',
            name='stars_spent_kopecks',
            field=models.BigIntegerField(default=0, verbose_name='Потрачено, копейки'),
        ),
        migrations.AlterField(
            model_name='studioproject',
            name='entry_mode',
            field=models.CharField(choices=[('description', 'С нуля')], default='description', max_length=20),
        ),
    ]
