# Generated by Django 6.0.6 on 2026-07-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0020_telegramuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='timezone_offset_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Часовой пояс (смещение от UTC, мин.)'),
        ),
    ]
