# Generated by Django 4.2 on 2026-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_batch_webhook_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusage',
            name='cost_kopecks',
            field=models.BigIntegerField(default=0, verbose_name='Списано, копейки'),
        ),
        migrations.AlterField(
            model_name='tokenusage',
            name='stars_charged',
            field=models.PositiveIntegerField(default=0, verbose_name='Списано звёзд (legacy)'),
        ),
    ]
