# Generated by Django 4.2 on 2026-07-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_backfill_kopecks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('key.created', 'Ключ создан'), ('key.deleted', 'Ключ удалён'), ('org.created', 'Организация создана'), ('org.updated', 'Организация обновлена'), ('member.added', 'Участник добавлен'), ('member.removed', 'Участник удалён'), ('invite.sent', 'Приглашение отправлено'), ('webhook.created', 'Webhook создан'), ('webhook.deleted', 'Webhook удалён'), ('batch.created', 'Пакет создан'), ('batch.cancelled', 'Пакет отменён'), ('sandbox.created', 'Песочница создана'), ('sandbox.deleted', 'Песочница остановлена')], db_index=True, max_length=50, verbose_name='Действие'),
        ),
    ]
