# Generated by Django 4.2 on 2026-07-06 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.CharField(choices=[('base', 'Base (Node 20 + Python 3.11)'), ('python', 'Python'), ('nodejs', 'Node.js'), ('nextjs', 'Next.js'), ('django', 'Django')], default='base', max_length=20, verbose_name='Шаблон')),
                ('size', models.CharField(choices=[('small', 'Small (1 vCPU / 1 GiB)'), ('standard', 'Standard (2 vCPU / 2 GiB)')], default='standard', max_length=20, verbose_name='Размер')),
                ('state', models.CharField(choices=[('starting', 'Запускается'), ('running', 'Работает'), ('stopped', 'Остановлена'), ('expired', 'Истекла'), ('failed', 'Ошибка')], db_index=True, default='starting', max_length=20, verbose_name='Состояние')),
                ('public_host', models.CharField(blank=True, max_length=255, verbose_name='Публичный хост')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Запущена')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='Остановлена')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Истекает')),
                ('ttl_seconds', models.PositiveIntegerField(default=300, verbose_name='TTL, сек')),
                ('reserved_kopecks', models.BigIntegerField(default=0, verbose_name='Резерв, коп.')),
                ('charged_kopecks', models.BigIntegerField(default=0, verbose_name='Списано, коп.')),
                ('exec_count', models.PositiveIntegerField(default=0, verbose_name='Число exec')),
                ('abuse_flagged', models.BooleanField(default=False, verbose_name='Флаг abuse')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandbox_sessions', to='api.apikey', verbose_name='API-ключ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Sandbox-сессия',
                'verbose_name_plural': 'Sandbox-сессии',
                'ordering': ['-created_at'],
            },
        ),
    ]
