# Generated by Django 4.2 on 2026-04-14 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.CharField(default='fas fa-cube', max_length=50, verbose_name='Иконка (FontAwesome)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название чата')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки генерации для чата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название нейросети')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='neural_avatars/', verbose_name='Аватар')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='URL аватара')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('cost_per_message', models.PositiveIntegerField(default=30, verbose_name='Стоимость за одно сообщение (⭐)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('model_name', models.CharField(blank=True, help_text='Например: deepseek/deepseek-chat-v3.1', max_length=100, null=True, verbose_name='Название модели (OpenRouter)')),
                ('is_default', models.BooleanField(default=False, help_text='Выберите одну модель, которая будет показываться в шапке по умолчанию', verbose_name='По умолчанию')),
                ('has_prompt', models.BooleanField(default=False, help_text='Использовать системный промт для этой нейросети', verbose_name='Встроенный промт')),
                ('prompt', models.TextField(blank=True, help_text='Системное сообщение, которое будет отправляться вместе с каждым запросом', null=True, verbose_name='Промт нейросети')),
                ('unlimited', models.BooleanField(default=False, help_text='Если включено, пользователи с указанным тарифом могут отправлять сообщения бесплатно (в пределах дневного лимита)', verbose_name='Безлимит')),
                ('messages_limit', models.PositiveIntegerField(default=0, help_text='Максимальное количество бесплатных сообщений в день для пользователей с указанным тарифом. 0 = без лимита.', verbose_name='Лимит сообщений в день')),
                ('handle_archive', models.BooleanField(default=False, help_text='Поддерживает архивы (.zip, .rar, .7z и т.д.)', verbose_name='Обработка архивов')),
                ('handle_text_files', models.BooleanField(default=False, help_text='Поддерживает .txt, .pdf, .doc, .docx, .odt и т.д.', verbose_name='Обработка текстовых файлов')),
                ('handle_photo', models.BooleanField(default=False, help_text='Поддерживает изображения (.jpg, .png, .gif, .webp и т.д.)', verbose_name='Обработка фото')),
                ('handle_video', models.BooleanField(default=False, help_text='Поддерживает видео (.mp4, .avi, .mov и т.д.)', verbose_name='Обработка видео')),
                ('provider', models.CharField(choices=[('openrouter', 'OpenRouter'), ('fal-ai', 'fal.ai')], default='openrouter', max_length=20, verbose_name='Провайдер')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='JSON конфигурация для моделей fal.ai (ui_settings, api_defaults, constraints, metadata)', verbose_name='Конфигурация модели (fal.ai)')),
                ('is_popular', models.BooleanField(default=False, help_text='Отображать в блоке "Популярные модели" на странице выбора', verbose_name='Популярная модель')),
                ('translate_to_english', models.BooleanField(default=False, help_text='Если включено, перед отправкой в fal.ai промт пользователя будет переведён на английский (через DeepSeek)', verbose_name='Перевод запросов на английский')),
                ('seo_title', models.CharField(blank=True, help_text='Если не указано, будет использовано название нейросети', max_length=200, null=True, verbose_name='SEO заголовок (title)')),
                ('seo_description', models.TextField(blank=True, help_text='Если не указано, будет использовано описание нейросети', null=True, verbose_name='SEO описание (description)')),
                ('seo_keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, null=True, verbose_name='SEO ключевые слова (keywords)')),
                ('is_direct', models.BooleanField(default=False, help_text='Показывать в футере в разделе "Прямые нейросети"', verbose_name='Прямые нейросети')),
                ('is_custom', models.BooleanField(default=False, help_text='Показывать в футере в разделе "Кастомные модели"', verbose_name='Кастомные модели')),
                ('max_tokens', models.PositiveIntegerField(default=0, help_text='0 = без ограничений', verbose_name='Максимум токенов в ответе')),
                ('max_input_tokens', models.PositiveIntegerField(default=0, help_text='0 = без ограничений. Обрезает текст сообщения пользователя до указанного количества символов.', verbose_name='Максимум токенов в запросе пользователя')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='aitext.category', verbose_name='Категория')),
                ('tariffs', models.ManyToManyField(blank=True, help_text='Пользователи с выбранными тарифами получают бесплатные сообщения в рамках дневного лимита', related_name='unlimited_networks', to='users.tariff', verbose_name='Тарифы для безлимита')),
            ],
            options={
                'verbose_name': 'Нейросеть',
                'verbose_name_plural': 'Нейросети',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент')], max_length=10)),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('files', models.JSONField(blank=True, default=list, verbose_name='Файлы')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Потрачено токенов')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('extracted_content', models.TextField(blank=True, null=True, verbose_name='Извлеченное содержимое файлов')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки генерации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plain_text', models.TextField(blank=True, verbose_name='Оригинальный текст без форматирования')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aitext.chat')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generated_images/%Y/%m/%d/', verbose_name='Файл (изображение или видео)')),
                ('prompt', models.TextField(blank=True, verbose_name='Промт (для генерации)')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='aitext.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сгенерированное изображение',
                'verbose_name_plural': 'Сгенерированные изображения',
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('file_size', models.IntegerField(verbose_name='Размер (байты)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME тип')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('pdf', 'PDF документ'), ('other', 'Другой файл')], default='image', max_length=20, verbose_name='Тип файла')),
                ('extracted_text', models.TextField(blank=True, null=True, verbose_name='Извлеченный текст')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('resolution', models.CharField(blank=True, max_length=20, verbose_name='Разрешение')),
                ('source', models.CharField(choices=[('uploaded', 'Загружено пользователем'), ('ai_generated', 'Сгенерировано AI')], default='uploaded', max_length=20, verbose_name='Источник')),
                ('model_id', models.CharField(blank=True, max_length=200, verbose_name='ID модели (для сгенерированных)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='aitext.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Прикрепленный файл',
                'verbose_name_plural': 'Прикрепленные файлы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Показывать только на главной')),
                ('show_everywhere', models.BooleanField(default=False, verbose_name='Показывать везде')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('neural_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aitext.neuralnetwork', verbose_name='Привязать к нейросети')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='aitext.neuralnetwork'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NeuralNetworkDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='aitext.neuralnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_network_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ежедневное использование нейросети',
                'verbose_name_plural': 'Ежедневное использование нейросетей',
                'unique_together': {('user', 'network', 'date')},
            },
        ),
    ]
