# Generated by Django 4.2 on 2026-06-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralnetwork',
            name='config_json',
            field=models.JSONField(blank=True, default=dict, help_text='JSON конфигурация для моделей изображений. api_defaults: {size, quality, style, n}. ui_settings, constraints, metadata', verbose_name='Конфигурация модели (изображения)'),
        ),
        migrations.AlterField(
            model_name='neuralnetwork',
            name='model_name',
            field=models.CharField(blank=True, help_text='Например: gpt-4o, claude-sonnet-4-6, deepseek-v3, flux-2-pro', max_length=100, null=True, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='neuralnetwork',
            name='provider',
            field=models.CharField(choices=[('openrouter', 'laozhang.ai (текст)'), ('fal-ai', 'laozhang.ai (изображения/видео)')], default='openrouter', max_length=20, verbose_name='Провайдер'),
        ),
    ]
