# Generated by Django 4.2 on 2026-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitext', '0002_alter_neuralnetwork_config_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralnetwork',
            name='cost_per_message',
            field=models.PositiveIntegerField(default=30, verbose_name='Стоимость за одно сообщение (зв.)'),
        ),
    ]
