# Generated by Django 4.2 on 2026-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitext', '0044_generatedimage_is_favorite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectauditentry',
            new_name='aitext_proj_project_5664bf_idx',
            old_name='aitext_proj_project_audit_idx',
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='cost_kopecks',
            field=models.BigIntegerField(default=0, help_text='Авторитетное поле цены (позволяет дробные ₽, например 50 = 0,50 ₽). 0 при создании = выводится из cost_per_message×100 один раз; далее оба поля независимы.', verbose_name='Стоимость за сообщение, копейки'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='kopecks_per_1k_tokens',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Для токенного биллинга через API-ключи. 0 = авто-расчёт из cost_kopecks.', max_digits=10, verbose_name='Копеек за 1000 токенов (dev-API)'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='cost_kopecks',
            field=models.BigIntegerField(default=0, verbose_name='Стоимость, копейки'),
        ),
        migrations.AlterField(
            model_name='neuralnetwork',
            name='stars_per_1k_tokens',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Legacy-поле, только для чтения через save()-синхронизацию. Редактируйте kopecks_per_1k_tokens.', max_digits=8, verbose_name='Звёзд за 1000 токенов (dev-API), legacy'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость (зв., legacy)'),
        ),
    ]
