# Generated by Django 6.0.6 on 2026-07-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitext', '0051_neuralnetwork_provider_cloudflare_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_description_en',
            field=models.TextField(blank=True, help_text='Если не указано, будет использовано описание нейросети', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_description_ru',
            field=models.TextField(blank=True, help_text='Если не указано, будет использовано описание нейросети', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_keywords_en',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_keywords_ru',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='Если не указано, будет использовано название нейросети', max_length=200, null=True, verbose_name='SEO заголовок (title)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_title_ru',
            field=models.CharField(blank=True, help_text='Если не указано, будет использовано название нейросети', max_length=200, null=True, verbose_name='SEO заголовок (title)'),
        ),
    ]
