# Generated by Django 6.0.6 on 2026-07-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitext', '0053_prompttemplate_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ind',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fa',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ind',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fa',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ind',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tr',
            field=models.CharField(max_length=500, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='description_ind',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_description_ar',
            field=models.TextField(blank=True, help_text='Если не указано, будет использовано описание нейросети', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_description_fa',
            field=models.TextField(blank=True, help_text='Если не указано, будет использовано описание нейросети', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_description_ind',
            field=models.TextField(blank=True, help_text='Если не указано, будет использовано описание нейросети', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_description_tr',
            field=models.TextField(blank=True, help_text='Если не указано, будет использовано описание нейросети', null=True, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_keywords_ar',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_keywords_fa',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_keywords_ind',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_keywords_tr',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, null=True, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_title_ar',
            field=models.CharField(blank=True, help_text='Если не указано, будет использовано название нейросети', max_length=200, null=True, verbose_name='SEO заголовок (title)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_title_fa',
            field=models.CharField(blank=True, help_text='Если не указано, будет использовано название нейросети', max_length=200, null=True, verbose_name='SEO заголовок (title)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_title_ind',
            field=models.CharField(blank=True, help_text='Если не указано, будет использовано название нейросети', max_length=200, null=True, verbose_name='SEO заголовок (title)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='seo_title_tr',
            field=models.CharField(blank=True, help_text='Если не указано, будет использовано название нейросети', max_length=200, null=True, verbose_name='SEO заголовок (title)'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='Текст промта'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='Текст промта'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='content_ind',
            field=models.TextField(null=True, verbose_name='Текст промта'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='Текст промта'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='title_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='title_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='title_ind',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='title_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
