# Generated by Django 6.0.6 on 2026-07-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitext', '0054_add_fa_tr_id_ar_translation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermemory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='aitext.project', verbose_name='Проект (скоуп)'),
        ),
    ]
