# Generated by Django 6.0.6 on 2026-08-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitext', '0057_deactivate_deepseek_v3'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('channel', models.CharField(choices=[('web', 'Веб'), ('telegram', 'Telegram')], default='web', max_length=16)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('provider', 'Ответ провайдера'), ('estimate', 'Локальная оценка (tiktoken)'), ('missing', 'Недоступно (обрыв клиента)')], default='missing', max_length=16)),
                ('flat_was_charged', models.BooleanField(default=False)),
                ('flat_kopecks', models.BigIntegerField(default=0)),
                ('cost_kopecks', models.BigIntegerField(default=0)),
                ('overage_kopecks', models.BigIntegerField(default=0)),
                ('settled_kopecks', models.BigIntegerField(default=0)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='aitext.message')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aitext.neuralnetwork')),
            ],
            options={
                'verbose_name': 'Расход токенов',
                'verbose_name_plural': 'Расход токенов',
                'indexes': [models.Index(fields=['-created_at', 'model_name'], name='aitext_mess_created_6dd2cf_idx')],
            },
        ),
    ]
